{{- if .Values.api.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gravitee.api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  env.dist: |
    ############## APIGROW MAIN CONFIGURATION ############## 
    APIZR_API_KEY=ZQvoqSZtRrueflUhqAXK
    APIZR_API_KEY_HEADER_NAME=x-apizr-apikey
    AUTOSWAGGER_FRONT_URL={{ index .Values.ui.ingress.hosts 0 }}
    COOKIE_DOMAIN=.example.com

    ############ JWT SECTION ###############
    JWT_COOKIE_NAME=apizr-login-cookie
    JWT_SECRET=45890GJKDLZEEF567890
    
    ############ SWAGGER PRODUCER SECTION ###############
    SWAGGER_PRODUCER_URL=https://design.example.com/generator
    SWAGGER_PRODUCER_APIKEY=PgUfDekIFAYmanUeRIQU
    
    ############# Gravitee configuration ################
    GRAVITEE_ENABLED=true
    GRAVITEE_MANAGEMENT_API_URL={{ .Values.apim.management.url }}
    GRAVITEE_COOKIE_NAME={{ .Values.apim.management.cookie.name }}
    GRAVITEE_ORGANIZATION=DEFAULT
    GRAVITEE_ENVIRONMENT=DEFAULT
{{- end -}}
